version: '3.9'
services:
  client-app:
    build: client-app
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app:cached
    image: client-app
    container_name: client-app
    tty: true
  server:
    build: server
    tty: true
    ports:
      - 8080:8080
    image: server
    container_name: server